name: 'Code Styling'

on:
  push:
    paths:
      - '**.php'
      - 'resources'
    branches:
      - main
  pull_request:
    paths:
      - '**.php'
      - 'resources'

jobs:
  code-styling:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/package-lock.json') }}
      - name: Install Node Modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Run Prettier
        run: npm run prettier

      - name: Run Pint
        uses: aglipanci/laravel-pint-action@2.3.1
