name: 'Code Styling'

on:
  push:
    paths:
      - '**.php'
      - 'resources'
    branches:
      - main
  pull_request:
    paths:
      - '**.php'
      - 'resources'

jobs:
  code-styling:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: 'npm'
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run prettier

      - name: Run Pint
        uses: aglipanci/laravel-pint-action@2.3.1
