name: "Code Styling"

on:
  push:
    paths:
      - '**.php'
      - 'resources'
  pull_request:
    paths:
      - '**.php'
      - 'resources'

jobs:
  code-styling:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Composer
        uses: php-actions/composer@v6
        with:
          php_extensions: intl zip sodium pcntl bcmath
          php_version: "8.2"
          args: --ignore-platform-req=ext-pcntl --ignore-platform-req=ext-bcmath

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier

      - name: Run Pint
        uses: aglipanci/laravel-pint-action@2.3.1
