name: Laravel Dusk Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-app-with-dusk:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    env:
      APP_URL: "http://127.0.0.1:8000"
      DB_USERNAME: root
      DB_PASSWORD: root
      MAIL_MAILER: log
      REDIS_HOST: localhost
      QUEUE_CONNECTION: redis
    steps:
      - uses: actions/checkout@v4
      - name: Install yt-dlp and ffmpeg
        run: |
          if ! command -v yt-dlp &> /dev/null || ! command -v ffmpeg &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y yt-dlp ffmpeg
          fi
      - name: Prepare The Environment
        run: cp .env.example .env
      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE \`pr0verter\` character set UTF8mb4 collate utf8mb4_bin;"
      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
      - name: Install Composer Dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Link Storage
        run: php artisan storage:link
      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver --detect
      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
      - uses: actions/setup-node@v4
        with:
          node-version: "21.7.3"
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json
      - run: npm run build
      - name: Migrate Database & Seed
        run: php artisan migrate:fresh --seed --force
      - name: Run Laravel Server
        run: php artisan serve --no-reload &
      - name: Run Laravel Reverb Server
        run: php artisan reverb:start --host="0.0.0.0" --port=8080 --no-interaction &
      - name: Run Laravel Horizon
        run: php artisan horizon &
      - name: Run Dusk Tests
        run: php artisan dusk
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tests/Browser/screenshots
      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: console
          path: tests/Browser/console
