name: 'PHPStan Check'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          php_extensions: intl zip sodium pcntl bcmath
          php_version: '8.2'
          args: --ignore-platform-reqs --optimize-autoloader --no-progress --prefer-dist --optimize-autoloader
      - uses: php-actions/phpstan@v3
        with:
          memory_limit: 2G
